# Generated by Django 2.2.6 on 2019-11-03 00:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('UsuId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('Tel', models.CharField(max_length=20)),
                ('UsuFechNac', models.DateField()),
                ('UsuUltimoLog', models.DateTimeField()),
                ('UsuVerificado', models.BooleanField(default=False)),
                ('user_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CondUrlFotLic', models.CharField(max_length=200)),
                ('CondId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('RutaId', models.AutoField(primary_key=True, serialize=False)),
                ('OrigenLat', models.FloatField()),
                ('DestinoLat', models.FloatField()),
                ('OrigenLon', models.FloatField()),
                ('DestinoLon', models.FloatField()),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_usu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('TipoCod', models.AutoField(primary_key=True, serialize=False)),
                ('TipoNom', models.CharField(max_length=40, unique=True)),
                ('CapMax', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('VehiculoId', models.AutoField(primary_key=True, serialize=False)),
                ('VehiculoMatr', models.CharField(max_length=8)),
                ('VehiculoColor', models.CharField(max_length=20)),
                ('TipoCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='accounts.Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('ViajeId', models.AutoField(primary_key=True, serialize=False)),
                ('ViajeFecha', models.DateTimeField()),
                ('CondId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_cond', to='accounts.Conductor')),
                ('VehiculoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_veh', to='accounts.Vehiculo')),
                ('ViajeRuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_ruta', to='accounts.Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='TieneVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CondId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiene_vehiculo_cond', to='accounts.Conductor')),
                ('VehiculoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiene_vehiculo_veh', to='accounts.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntaje', models.PositiveIntegerField()),
                ('Descr', models.CharField(max_length=200)),
                ('AutorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntaje_autor', to=settings.AUTH_USER_MODEL)),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntaje_usu', to=settings.AUTH_USER_MODEL)),
                ('ViajeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntaje_viaje', to='accounts.Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Participa_Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoraSubida', models.TimeField()),
                ('OrigenLat', models.FloatField()),
                ('DestinoLat', models.FloatField()),
                ('OrigenLon', models.FloatField()),
                ('DestinoLon', models.FloatField()),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particia_viaje_usu', to=settings.AUTH_USER_MODEL)),
                ('ViajeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participa_viaje_viaje', to='accounts.Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Historial_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogFecha', models.DateField()),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_login', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Amigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FecIniAmistad', models.DateField()),
                ('UsuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amigo_usu', to=settings.AUTH_USER_MODEL)),
                ('UsuIdAmigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usu_amigo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
