# Generated by Django 2.2.6 on 2019-11-03 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participa_viaje',
            name='DestinoLon',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='UsuFechNac',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='UsuUltimoLog',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
