# Generated by Django 2.2.6 on 2019-11-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='participa_viaje',
            name='DestinoLon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participa_viaje',
            name='DestinoLat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participa_viaje',
            name='OrigenLat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='participa_viaje',
            name='OrigenLon',
            field=models.FloatField(default=0),
        ),
    ]
